### ISSUE TITLE
Create automated deployment template using 'Blue Button'

### ISSUE THREAD

**Issue by stylesm** [research-software-reactor/cyclecloud#14]
Probably excluding identity as this is being worked on separately.

**Comment by leestott** [comment]
Issue is that the existing Azure Deploy at https://docs.microsoft.com/en-us/azure/cyclecloud/quickstart-install-cyclecloud

Requires the following information to be added 
Basics:
Subscription: If you have more than one active Azure subscription, select the one to use here
Resource Group: Enter the name of a (new) resource group that will hold everything generated by this quickstart (e.g. MyQuickstart)
Location: Select a region in which to store your instance

Settings:
Tenant ID: The tenant from the service principal above
Application ID: The appId from the service principal above
Application Secret: The password from the service principal above
SSH Public Key: The public key used to log into the CycleCloud VM
Username: The username for the CycleCloud VM. Use your Azure Portal username without the domain (e.g. johnsmith instead of *johnsmith@domain.com*)
The remaining fields can be left as is. Agree to the terms and conditions, and click Purchase. Note that the CycleCloud product is free but you are still paying for the core hours used in Azure.

The deployment process runs an installation script as a custom script extension, which installs and sets up CycleCloud. This process takes between 5 and 8 mins.

The deployment button is based on the community contribution https://github.com/CycleCloudCommunity/cyclecloud_arm

The issue is this uses service principals and most users aren't assigned service principals

**Comment by stylesm** [comment]
The 'blue button' basically deploys an ARM JSON. Using a single ARM it's not possible to manage assigning the necessary access based on the newly-created VMs. #13 provides this one-command solution using Powershell/ARM and is resolved.
